// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf C++ Version: 6.31.0

#include "sensor.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ReadRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sensor_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReadRequest::ReadRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReadRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadRequestDefaultTypeInternal() {}
  union {
    ReadRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadRequestDefaultTypeInternal _ReadRequest_default_instance_;

inline constexpr HomeSensorData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        temperature_{0},
        light_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HomeSensorData::HomeSensorData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HomeSensorData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HomeSensorDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HomeSensorDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HomeSensorDataDefaultTypeInternal() {}
  union {
    HomeSensorData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HomeSensorDataDefaultTypeInternal _HomeSensorData_default_instance_;

inline constexpr ReadReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        home_data_{nullptr},
        level_{static_cast< ::Level >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ReadReply::ReadReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReadReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadReplyDefaultTypeInternal() {}
  union {
    ReadReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadReplyDefaultTypeInternal _ReadReply_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_sensor_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_sensor_2eproto = nullptr;
const ::uint32_t
    TableStruct_sensor_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ReadRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ReadRequest, _impl_.sensor_type_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::HomeSensorData, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::HomeSensorData, _impl_.temperature_),
        PROTOBUF_FIELD_OFFSET(::HomeSensorData, _impl_.light_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ReadReply, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ReadReply, _impl_.home_data_),
        PROTOBUF_FIELD_OFFSET(::ReadReply, _impl_.level_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ReadRequest)},
        {5, sizeof(::HomeSensorData)},
        {12, sizeof(::ReadReply)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_ReadRequest_default_instance_._instance,
    &::_HomeSensorData_default_instance_._instance,
    &::_ReadReply_default_instance_._instance,
};
const char descriptor_table_protodef_sensor_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014sensor.proto\"\"\n\013ReadRequest\022\023\n\013sensor_"
    "type\030\002 \001(\005\"4\n\016HomeSensorData\022\023\n\013temperat"
    "ure\030\001 \001(\005\022\r\n\005light\030\002 \001(\005\"F\n\tReadReply\022\"\n"
    "\thome_data\030\001 \001(\0132\017.HomeSensorData\022\025\n\005lev"
    "el\030\002 \001(\0162\006.Level*M\n\005Level\022\024\n\020SENSOR_LEVE"
    "L_LOW\020\000\022\027\n\023SENSOR_LEVEL_MEDIUM\020\002\022\025\n\021SENS"
    "OR_LEVEL_HIGH\020\00422\n\006Sensor\022(\n\nReadSensor\022"
    "\014.ReadRequest\032\n.ReadReply\"\000b\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_sensor_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sensor_2eproto = {
    false,
    false,
    320,
    descriptor_table_protodef_sensor_2eproto,
    "sensor.proto",
    &descriptor_table_sensor_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_sensor_2eproto::offsets,
    file_level_enum_descriptors_sensor_2eproto,
    file_level_service_descriptors_sensor_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Level_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_sensor_2eproto);
  return file_level_enum_descriptors_sensor_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Level_internal_data_[] = {
    65536u, 32u, 10u, };
// ===================================================================

class ReadRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReadRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_._has_bits_);
};

ReadRequest::ReadRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ReadRequest)
}
ReadRequest::ReadRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReadRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ReadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ReadRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sensor_type_ = {};
}
ReadRequest::~ReadRequest() {
  // @@protoc_insertion_point(destructor:ReadRequest)
  SharedDtor(*this);
}
inline void ReadRequest::SharedDtor(MessageLite& self) {
  ReadRequest& this_ = static_cast<ReadRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReadRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadRequest(arena);
}
constexpr auto ReadRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReadRequest),
                                            alignof(ReadRequest));
}
constexpr auto ReadRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReadRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReadRequest>(), &ReadRequest::ByteSizeLong,
              &ReadRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_._cached_size_),
          false,
      },
      &ReadRequest::kDescriptorMethods,
      &descriptor_table_sensor_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadRequest_class_data_ =
        ReadRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadRequest_class_data_.tc_table);
  return ReadRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ReadRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReadRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ReadRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 sensor_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReadRequest, _impl_.sensor_type_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_.sensor_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sensor_type = 2;
    {PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_.sensor_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ReadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ReadRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sensor_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReadRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReadRequest& this_ = static_cast<const ReadRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReadRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReadRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ReadRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 sensor_type = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_sensor_type(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReadRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReadRequest::ByteSizeLong(const MessageLite& base) {
  const ReadRequest& this_ = static_cast<const ReadRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReadRequest::ByteSizeLong() const {
  const ReadRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ReadRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 sensor_type = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_sensor_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReadRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadRequest*>(&to_msg);
  auto& from = static_cast<const ReadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReadRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_impl_.sensor_type_ = from._impl_.sensor_type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadRequest::CopyFrom(const ReadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadRequest::InternalSwap(ReadRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.sensor_type_, other->_impl_.sensor_type_);
}

::google::protobuf::Metadata ReadRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HomeSensorData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HomeSensorData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_._has_bits_);
};

HomeSensorData::HomeSensorData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HomeSensorData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:HomeSensorData)
}
HomeSensorData::HomeSensorData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HomeSensorData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HomeSensorData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE HomeSensorData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void HomeSensorData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, temperature_),
           0,
           offsetof(Impl_, light_) -
               offsetof(Impl_, temperature_) +
               sizeof(Impl_::light_));
}
HomeSensorData::~HomeSensorData() {
  // @@protoc_insertion_point(destructor:HomeSensorData)
  SharedDtor(*this);
}
inline void HomeSensorData::SharedDtor(MessageLite& self) {
  HomeSensorData& this_ = static_cast<HomeSensorData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HomeSensorData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HomeSensorData(arena);
}
constexpr auto HomeSensorData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HomeSensorData),
                                            alignof(HomeSensorData));
}
constexpr auto HomeSensorData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HomeSensorData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HomeSensorData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HomeSensorData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HomeSensorData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HomeSensorData>(), &HomeSensorData::ByteSizeLong,
              &HomeSensorData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_._cached_size_),
          false,
      },
      &HomeSensorData::kDescriptorMethods,
      &descriptor_table_sensor_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HomeSensorData_class_data_ =
        HomeSensorData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HomeSensorData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HomeSensorData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HomeSensorData_class_data_.tc_table);
  return HomeSensorData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
HomeSensorData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HomeSensorData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::HomeSensorData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 light = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HomeSensorData, _impl_.light_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.light_)}},
    // int32 temperature = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HomeSensorData, _impl_.temperature_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.temperature_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 temperature = 1;
    {PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.temperature_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 light = 2;
    {PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.light_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HomeSensorData::Clear() {
// @@protoc_insertion_point(message_clear_start:HomeSensorData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.temperature_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.light_) -
        reinterpret_cast<char*>(&_impl_.temperature_)) + sizeof(_impl_.light_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HomeSensorData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HomeSensorData& this_ = static_cast<const HomeSensorData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HomeSensorData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HomeSensorData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:HomeSensorData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 temperature = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_temperature(), target);
  }

  // int32 light = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_light(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HomeSensorData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HomeSensorData::ByteSizeLong(const MessageLite& base) {
  const HomeSensorData& this_ = static_cast<const HomeSensorData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HomeSensorData::ByteSizeLong() const {
  const HomeSensorData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:HomeSensorData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // int32 temperature = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_temperature());
    }
    // int32 light = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_light());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HomeSensorData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HomeSensorData*>(&to_msg);
  auto& from = static_cast<const HomeSensorData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HomeSensorData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.temperature_ = from._impl_.temperature_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.light_ = from._impl_.light_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HomeSensorData::CopyFrom(const HomeSensorData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HomeSensorData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HomeSensorData::InternalSwap(HomeSensorData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.light_)
      + sizeof(HomeSensorData::_impl_.light_)
      - PROTOBUF_FIELD_OFFSET(HomeSensorData, _impl_.temperature_)>(
          reinterpret_cast<char*>(&_impl_.temperature_),
          reinterpret_cast<char*>(&other->_impl_.temperature_));
}

::google::protobuf::Metadata HomeSensorData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReadReply::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReadReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReadReply, _impl_._has_bits_);
};

ReadReply::ReadReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ReadReply)
}
PROTOBUF_NDEBUG_INLINE ReadReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ReadReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ReadReply::ReadReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReadReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.home_data_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.home_data_)
                : nullptr;
  _impl_.level_ = from._impl_.level_;

  // @@protoc_insertion_point(copy_constructor:ReadReply)
}
PROTOBUF_NDEBUG_INLINE ReadReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ReadReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, home_data_),
           0,
           offsetof(Impl_, level_) -
               offsetof(Impl_, home_data_) +
               sizeof(Impl_::level_));
}
ReadReply::~ReadReply() {
  // @@protoc_insertion_point(destructor:ReadReply)
  SharedDtor(*this);
}
inline void ReadReply::SharedDtor(MessageLite& self) {
  ReadReply& this_ = static_cast<ReadReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.home_data_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReadReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadReply(arena);
}
constexpr auto ReadReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReadReply),
                                            alignof(ReadReply));
}
constexpr auto ReadReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReadReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReadReply>(), &ReadReply::ByteSizeLong,
              &ReadReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadReply, _impl_._cached_size_),
          false,
      },
      &ReadReply::kDescriptorMethods,
      &descriptor_table_sensor_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadReply_class_data_ =
        ReadReply::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadReply_class_data_.tc_table);
  return ReadReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
ReadReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReadReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ReadReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ReadReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Level level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReadReply, _impl_.level_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.level_)}},
    // .HomeSensorData home_data = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.home_data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .HomeSensorData home_data = 1;
    {PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.home_data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Level level = 2;
    {PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.level_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::HomeSensorData>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ReadReply::Clear() {
// @@protoc_insertion_point(message_clear_start:ReadReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.home_data_ != nullptr);
    _impl_.home_data_->Clear();
  }
  _impl_.level_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReadReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReadReply& this_ = static_cast<const ReadReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReadReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReadReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ReadReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .HomeSensorData home_data = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.home_data_, this_._impl_.home_data_->GetCachedSize(), target,
        stream);
  }

  // .Level level = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_level(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReadReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReadReply::ByteSizeLong(const MessageLite& base) {
  const ReadReply& this_ = static_cast<const ReadReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReadReply::ByteSizeLong() const {
  const ReadReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ReadReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .HomeSensorData home_data = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.home_data_);
    }
    // .Level level = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_level());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReadReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadReply*>(&to_msg);
  auto& from = static_cast<const ReadReply&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ReadReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.home_data_ != nullptr);
      if (_this->_impl_.home_data_ == nullptr) {
        _this->_impl_.home_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.home_data_);
      } else {
        _this->_impl_.home_data_->MergeFrom(*from._impl_.home_data_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.level_ = from._impl_.level_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadReply::CopyFrom(const ReadReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReadReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadReply::InternalSwap(ReadReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.level_)
      + sizeof(ReadReply::_impl_.level_)
      - PROTOBUF_FIELD_OFFSET(ReadReply, _impl_.home_data_)>(
          reinterpret_cast<char*>(&_impl_.home_data_),
          reinterpret_cast<char*>(&other->_impl_.home_data_));
}

::google::protobuf::Metadata ReadReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_sensor_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
