// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sensor.proto

#include "sensor.pb.h"
#include "sensor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* Sensor_method_names[] = {
  "/Sensor/ReadSensor",
};

std::unique_ptr< Sensor::Stub> Sensor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Sensor::Stub> stub(new Sensor::Stub(channel, options));
  return stub;
}

Sensor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReadSensor_(Sensor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Sensor::Stub::ReadSensor(::grpc::ClientContext* context, const ::ReadRequest& request, ::ReadReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ReadRequest, ::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadSensor_, context, request, response);
}

void Sensor::Stub::async::ReadSensor(::grpc::ClientContext* context, const ::ReadRequest* request, ::ReadReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ReadRequest, ::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadSensor_, context, request, response, std::move(f));
}

void Sensor::Stub::async::ReadSensor(::grpc::ClientContext* context, const ::ReadRequest* request, ::ReadReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadSensor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ReadReply>* Sensor::Stub::PrepareAsyncReadSensorRaw(::grpc::ClientContext* context, const ::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ReadReply, ::ReadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadSensor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ReadReply>* Sensor::Stub::AsyncReadSensorRaw(::grpc::ClientContext* context, const ::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadSensorRaw(context, request, cq);
  result->StartCall();
  return result;
}

Sensor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sensor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sensor::Service, ::ReadRequest, ::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Sensor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ReadRequest* req,
             ::ReadReply* resp) {
               return service->ReadSensor(ctx, req, resp);
             }, this)));
}

Sensor::Service::~Service() {
}

::grpc::Status Sensor::Service::ReadSensor(::grpc::ServerContext* context, const ::ReadRequest* request, ::ReadReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


